/**
 * Stripe Webhook Test Script
 * 
 * This script simulates a Stripe webhook event for testing the webhook handler.
 * Usage: npx ts-node scripts/send_stripe_webhook.ts
 */

import Stripe from 'stripe';

const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY || '';
const WEBHOOK_ENDPOINT = process.env.SUPABASE_URL 
  ? `${process.env.SUPABASE_URL}/functions/v1/stripe-webhook`
  : 'http://localhost:54321/functions/v1/stripe-webhook';

if (!STRIPE_SECRET_KEY) {
  console.error('❌ STRIPE_SECRET_KEY environment variable is not set');
  process.exit(1);
}

const stripe = new Stripe(STRIPE_SECRET_KEY, {
  apiVersion: '2024-06-20',
});

async function sendTestWebhook() {
  console.log('🚀 Sending test webhook to:', WEBHOOK_ENDPOINT);
  
  try {
    // Create a test checkout session completed event
    const event: Stripe.Event = {
      id: `evt_test_${Date.now()}`,
      object: 'event',
      api_version: '2024-06-20',
      created: Math.floor(Date.now() / 1000),
      type: 'checkout.session.completed',
      data: {
        object: {
          id: `cs_test_${Date.now()}`,
          object: 'checkout.session',
          mode: 'subscription',
          customer: 'cus_test_123',
          subscription: 'sub_test_123',
          status: 'complete',
          payment_status: 'paid',
        } as any,
      },
      livemode: false,
      pending_webhooks: 0,
      request: {
        id: null,
        idempotency_key: null,
      },
    };

    console.log('📦 Event payload:', JSON.stringify(event, null, 2));
    
    // Send the webhook
    const response = await fetch(WEBHOOK_ENDPOINT, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'stripe-signature': 'test_signature', // In real scenario, this would be generated by Stripe
      },
      body: JSON.stringify(event),
    });

    const result = await response.json();
    
    if (response.ok) {
      console.log('✅ Webhook sent successfully:', result);
    } else {
      console.error('❌ Webhook failed:', result);
    }
  } catch (error) {
    console.error('❌ Error sending webhook:', error);
  }
}

sendTestWebhook();
